<a href="https://colab.research.google.com/github/Amimo-cell/datascience/blob/main/Lesson3missing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import io
from google.colab import files

In [2]:
# allow us to import data
data= files.upload()

Saving Diabetes Missing Data.csv to Diabetes Missing Data.csv

In [3]:
#converting the file into a dataframe
sample_submission = pd.read_csv(io.StringIO(data['Diabetes Missing Data.csv'].decode('utf-8')))

In [4]:
#view the dataframe
sample_submission.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [6]:
# Generating data info
sample_submission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Pregnant           768 non-null    int64
 1   Glucose            763 non-null    float64
 2   Diastolic_BP       733 non-null    float64
 3   Skin_Fold          541 non-null    float64
 4   Serum_Insulin      394 non-null    float64
 5   BMI                757 non-null    float64
 6   Diabetes_Pedigree  768 non-null    float64
 7   Age                768 non-null    int64
 8   Class              768 non-null    int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB

In [7]:
# Getting the missing data
sample_submission.isnull().sum()

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [8]:
#drop missing values in Glucose
sample_submission.dropna(subset=["Glucose"],axis=0, inplace=True)

In [9]:
sample_submission.isnull().sum()

Pregnant               0
Glucose                0
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        370
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [10]:
# Replace Null values in Diastolic_BP with zero
sample_submission["Diastolic_BP"]=sample_submission["Diastolic_BP"].fillna(0)
sample_submission.isnull().sum()

Pregnant               0
Glucose                0
Diastolic_BP           0
Skin_Fold            227
Serum_Insulin        370
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [11]:
# calculate the mean for skin_fold values
mean=sample_submission['Skin_Fold'].mean()

In [17]:
# Replace Null values in Skin_Fold with average value
sample_submission["Skin_Fold"].replace(np.NAN,mean)
sample_submission.isnull().sum()

Pregnant               0
Glucose                0
Diastolic_BP           0
Skin_Fold              0
Serum_Insulin        370
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [15]:
#replace null values in Skin_Fold with average value
sample_submission['Skin_Fold'].fillna(sample_submission['Skin_Fold'].mean(), inplace=True)
sample_submission.isnull().sum()

<ipython-input-15-8e196bc893bc>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sample_submission['Skin_Fold'].fillna(sample_submission['Skin_Fold'].mean(), inplace=True)

Pregnant               0
Glucose                0
Diastolic_BP           0
Skin_Fold              0
Serum_Insulin        370
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64